#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <flipper_canbus_icons.h>

int32_t flipper_canbus_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm flipper_canbus!");

    return 0;
}
